title: RMS Titanic Data Analysis
description: "A Jekyll Blog Theme Presenting Analysis on RMS Data from Kaggle Along with some Miscellaneous Analysis."
author:
  name: "Ikageng Sebesho"
  email: "Ikageng@Hotmail.com"
  url: "https://ashishchaudhary.in/hacker-blog"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "*Ikageng Sebesho"
year : "2025"
